kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: scylla-ssd
  annotations:
    storageclass.beta.kubernetes.io/is-default-class: "true"
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
  namespace: nalej
provisioner: k8s.io/minikube-hostpath

