apiVersion: v1
kind: Service
metadata:
  labels:
    cluster: management
    component: scylladb
  name: scylladb
  namespace: nalej
spec:
  selector:
    cluster: management
    component: scylladb
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 9042
    targetPort: 9042
