
apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: scylla
  labels:
    app: scylla
    scylla-provider-version: VERSION
  namespace: nalej
spec:
  serviceName: scylla
  replicas: 3
  selector:
    matchLabels:
      app: scylla
  template:
    metadata:
      labels:
        app: scylla
    spec:
      containers:
        - name: scylla
          image: scylladb/scylla:2.0.0
          imagePullPolicy: IfNotPresent
          args: ["--seeds", "scylla-0.scylla.nalej.svc.cluster.local"]
          ports:
            - containerPort: 7000
              name: intra-node
            - containerPort: 7001
              name: tls-intra-node
            - containerPort: 7199
              name: jmx
            - containerPort: 9042
              name: cql
          securityContext:
            capabilities:
              add:
                - IPC_LOCK
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "PID=$(pidof scylla) && kill $PID && while ps -p $PID > /dev/null; do sleep 1; done"]
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          readinessProbe:
            exec:
              command:
                - /bin/bash
                - -c
                - exec
                - /opt/ready-probe.sh
            initialDelaySeconds: 15
            timeoutSeconds: 5
          volumeMounts:
            - name: scylla-data
              mountPath: /var/lib/scylla
            - name: scylla-ready-probe
              mountPath: /opt/ready-probe.sh
              subPath: ready-probe.sh
            - name: scylla-ready-probe
              mountPath: /etc/scylla/scylla.yaml
              subPath: scylla.yaml
      volumes:
        - name: scylla-data
          emptyDir: {}
        - name: scylla-ready-probe
          configMap:
            name: scylla


