apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: scylla-data
  namespace: nalej
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: managed-premium
  resources:
    requests:
      storage: 10Gi
